parameters:
#    shopify_shopify.example.class: Shopify\ShopifyBundle\Example

services:
#    shopify_shopify.example:
#        class: %shopify_shopify.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
